# Generated by Django 5.2.8 on 2025-11-26 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=250)),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(6)])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_subscribed', models.BooleanField(default=False)),
            ],
        ),
    ]
