# Generated by Django 5.2.8 on 2025-11-26 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0004_alter_review_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='viewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orm.viewer'),
        ),
    ]
